version: '3'
services:
  postgres:
    container_name: shift_postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sub
    ports:
      - '5555:5432'